version: "3"

services:
  cognito:
    image: ghcr.io/antimatter-studios/cognito-local:latest
    build:
      context: .
      cache_from:
        - ghcr.io/antimatter-studios/cognito-local:latest
    ports:
      - 9230:9230
    volumes:
      - $PWD/data:/app/data
    environment:
      - DEBUG=1
